# Generated by Django 3.2.6 on 2021-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210826_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Designation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
